<script lang="ts">
    import Saos from "saos";

	
  // @ts-ignore
  
  import {Carousel,Modal,TopList,Categorias,Why,Comentarios,ProductList} from "$components";

    // @ts-ignore
  /** @type {import('./$types').PageData} */
  export let data;
 
  // console.log($product)
  const productos = data.products.slice(0,4).map((val:any)=>{

      return {
      title:val.node.title,
      price:val.node.priceRange.minVariantPrice.amount,
      src:val.node.images.edges[0].node.url,
      href:"/productos/"+val.node.id
    }
    

  })




  let content= [{
    leyenda:"Mejora tu vida sexual con nuestros productos de alta calidad.",
    imagen:"sextoys.png",
    href:"#"
  },
  {
    leyenda:"Mejora tu vida",
    imagen:"sextoys.png",
    href:"#"
  }
  ]

</script>
<style>
  /* ----------------------------------------------
 * Generated by Animista on 2023-3-5 14:18:14
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bottom
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
            transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}
@keyframes -global-fade-in-bottom {
  0% {
    -webkit-transform: translateY(50px);
            transform: translateY(50px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    opacity: 1;
  }
}

</style>




<Modal/>
<Carousel content={content}/>
<Saos once={true} animation={'fade-in-bottom  2s cubic-bezier(0.35, 0.5, 0.65, 0.95) both'}>
  <TopList products= {productos}/>
</Saos>
<div class="my-4 ">
  <img
  src="/sex.webp"
  class="w-full">
</div>
<Categorias/>
<Why/>
<Comentarios/>