<script>
      import Saos from "saos"
</script>
<style>
    /* ----------------------------------------------
 * Generated by Animista on 2023-3-5 14:33:45
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes -global-slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
/* ----------------------------------------------
 * Generated by Animista on 2023-3-5 14:36:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-right
 * ----------------------------------------
 */
 @-webkit-keyframes slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}
@keyframes -global-slide-in-right {
  0% {
    -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
            transform: translateX(0);
    opacity: 1;
  }
}

</style>
<div>
    <div class="lg:mt-20 mt-10 flex flex-col items-center">
        <h1 class=" text-3xl font-principal  text-naranjasins">Explora nuestros</h1>
        <h1 class=" text-5xl font-principal  text-naranjasins">Productos</h1>
      </div>
</div>
<div class="group   mt-8 grid grid-cols-2 px-10 content-between gap-8">
    <Saos animation={"slide-in-left 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both"}>
    <div class="">
        <div>
            <img class="hover:opacity-75" src="/rebajas.webp">
        </div>
        <div class="mt-4">
            <img class="hover:opacity-75" src="/rebajas.webp">
        </div>
    </div>
    </Saos>
    <Saos animation={"slide-in-right 2s cubic-bezier(0.250, 0.460, 0.450, 0.940) both"}>
    <div>
        <div class="mt-4 lg:mt-0">
            <img class="hover:opacity-75" src="/rebajas.webp">
        </div>
        <div  class="mt-4">
            <img class="hover:opacity-75" src="/rebajas.webp">
        </div>
    </div>
    </Saos>

</div>